name: Python PRMS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        # You can create a tests folder or test scripts
        if [ -f test_prms.py ]; then
          python test_prms.py
        else
          echo "No test file found, skipping tests."
        fi

    - name: Check for syntax errors
      run: |
        python -m py_compile $(find . -name "*.py")

    - name: Success Message
      run: echo "✅ PRMS project code checked successfully!"
